# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Byonjiwa
email: aloepig@gmail.com
description: "Since 2004" # the subpath of your site, e.g. /blog
url: "http://byonjiwa.com" # the base hostname & protocol for your site
twitter_username: giantjiwa
github_username:  aloepig

# Pageing
gems: [jekyll-paginate]
paginate: 50
paginate_path: "page:num/"

# Build settings
markdown: kramdown